#!/usr/bin/env bash

HACKFEST=${HOME}/Cloud/Projects/hackfest2
MODELS=${HOME}/Cloud/Models/hackfest
FILES=`find $MODELS | grep '.gltf$'`

for f in $FILES; do
	cp "${f}" "${HACKFEST}/assets/import"
done
