#!/usr/bin/env bash

set -e

WORKSPACE=`i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name' | cut -d\" -f2`
XTITLE=`xtitle`

if [[ $WORKSPACE == 1 ]]; then
	[[ ${XTITLE} == "tmux" ]] && tmux neww || $TERMINAL tmux &
else
	$TERMINAL &
fi

disown
