#!/usr/bin/bash

wallpaper=`cat ~/Cloud/Pictures/Wallpapers/Log | tail -n 1`
mkdir -p ~/Cloud/Pictures/Wallpapers-Retired/$wallpaper
echo mv ~/Cloud/Pictures/Wallpapers/$wallpaper ~/Cloud/Pictures/Wallpapers-Retired/$wallpaper
