#!/usr/bin/env bash

shopt -s globstar
shopt -s nullglob

bin="$HOME/.local/bin"
cd "$bin"

PATH="${bin}:${PATH}"
for folder in **/; do
	real=`realpath $folder`
	PATH="${real}:${PATH}"
done

cd 
export PATH
